### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by binogoli** [noahzn/LISU#1]
Hi My Friend，
  May I ask which version of Python you team used in this paper. Here I met some wired issues here, could you pls provide some hints?
```
UnboundLocalError: local variable 'smap_oh' referenced before assignment
```

**Comment by noahzn** [comment]
Hi @binogoli , 
I used Python 3.7.4. 
May I know from which line did you get this error? This could be a problem related to '--multiple-GPUs'

**Comment by binogoli** [comment]
Hi @noahzn,
  Tks for your replying, the error comes from main.py line 262 and the detail information is attached below
```
Traceback (most recent call last):
  File "C:/Users/bingo/Desktop/LISU/main.py", line 430, in <module>
    main(sys.argv[1:])
  File "C:/Users/bingo/Desktop/LISU/main.py", line 420, in main
    train_and_val(args, Net, opt_Net, Net2, opt_Net2, trainloader, valloader, best_pred=best_pred)
  File "C:/Users/bingo/Desktop/LISU/main.py", line 151, in train_and_val
    iou, loss_val, acc, pre_val, lbl_val, avgacc = val(args, Decomp, opt_Decomp, Enhance, opt_Enhance, trainloader, valloader)
  File "C:/Users/bingo/Desktop/LISU/main.py", line 262, in val
    return np.sum(np.nanmean(iu[1:])), np.mean(loss_record), acc, smap_oh, label, np.sum(np.nanmean(acc_cls[1:]))
UnboundLocalError: local variable 'smap_oh' referenced before assignment

Process finished with exit code 1
```

  BTW, talking about the '--multiple-GPUs' option, I also have another question, in main.py line 189,  about val function
```
def val(args, Decomp, opt_Decomp, Enhance, opt_Enhance, trainloader, valloader, best_pred=0.0):
    print('start val!')
    ....
    acc, acc_cls, iou, _, iu = utils.label_accuracy_score(lbls, preds, args.num_classes)
```
  If the ==args.multiple_GPUs== option is false,  all the parameters at the end of function wil  output zero since no value is given, do I need to set ==args.multiple_GPUs== true in the training process even though I have only one GPU.

**Comment by noahzn** [comment]
Hi, I'm sorry that actually the released code does not provide multiple-GPU training. You can simply remove line 210 and line 212. I will try to update the code to remove the confusing part. But, at this moment you can do small modifications. Please contact me if you have more questions.

**Comment by binogoli** [comment]
Hi @noahzn,
  I modified the code as your suggestion and it looks like the projects is working regularly now.
  Actually I only own one GPU, so the current version is totally okay for me.
  I will contact you once I encounter some other problems.
  Tks again for your efforts on this issue. : )
